cask_args appdir: '/Applications'

# Prerequisites for some of the apps
tap 'homebrew/bundle'
tap 'homebrew/cask'
brew 'java'
cask 'xquartz'

# Stuff
brew 'archey'
brew 'asciidoctor'
brew 'coreutils'
brew 'ffmpeg'
brew 'flac'
brew 'freetype'
brew 'go'
brew 'graphviz'
brew 'grc'
brew 'highlight'
brew 'htop'
brew 'hub'
brew 'icu4c'
brew 'imagemagick'
brew 'jp2a'
brew 'jpeg'
brew 'less'
brew 'libplist'
brew 'libpng'
brew 'libtiff'
brew 'libtool'
brew 'libusb'
brew 'libzip'
brew 'node'
brew 'npm'
brew 'pmd'
brew 'pyenv'
brew 'readline'
brew 'spark'
brew 'tmux'
brew 'watch'
brew 'weechat'
brew 'yarn'

# More stuff
cask 'aerial'
cask 'alfred'
cask 'brave-browser'
cask 'homebrew/cask/dash'
cask 'gimp'
cask 'google-drive-file-stream'
cask 'inkscape'
cask 'iterm2'
cask 'lastpass'
cask 'postman'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'qlvideo'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'quicklookase'
cask 'slack'
cask 'spotify'
cask 'visual-studio-code'
cask 'webpquicklook'
